# automatically generated by the FlatBuffers compiler, do not modify

# namespace: StreamCPIInfo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Partition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Partition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPartition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Partition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Partition
    def GraphMetadata(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from StreamCPIInfo.GraphMetadata import GraphMetadata
            obj = GraphMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Partition
    def PartitionConfiguration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from StreamCPIInfo.PartitionConfiguration import PartitionConfiguration
            obj = PartitionConfiguration()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Partition
    def Runtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from StreamCPIInfo.RunTime import RunTime
            obj = RunTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Partition
    def MemoryConsumption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from StreamCPIInfo.MemoryConsumption import MemoryConsumption
            obj = MemoryConsumption()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Partition
    def Metrics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from StreamCPIInfo.PartitionMetrics import PartitionMetrics
            obj = PartitionMetrics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PartitionStart(builder):
    builder.StartObject(5)

def Start(builder):
    PartitionStart(builder)

def PartitionAddGraphMetadata(builder, graphMetadata):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(graphMetadata), 0)

def AddGraphMetadata(builder, graphMetadata):
    PartitionAddGraphMetadata(builder, graphMetadata)

def PartitionAddPartitionConfiguration(builder, partitionConfiguration):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(partitionConfiguration), 0)

def AddPartitionConfiguration(builder, partitionConfiguration):
    PartitionAddPartitionConfiguration(builder, partitionConfiguration)

def PartitionAddRuntime(builder, runtime):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(runtime), 0)

def AddRuntime(builder, runtime):
    PartitionAddRuntime(builder, runtime)

def PartitionAddMemoryConsumption(builder, memoryConsumption):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(memoryConsumption), 0)

def AddMemoryConsumption(builder, memoryConsumption):
    PartitionAddMemoryConsumption(builder, memoryConsumption)

def PartitionAddMetrics(builder, metrics):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(metrics), 0)

def AddMetrics(builder, metrics):
    PartitionAddMetrics(builder, metrics)

def PartitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return PartitionEnd(builder)
